version: "3.5"
services:
  webapp:
    image: vulnerables/web-dvwa
    expose:
      - "80"
  nginx:
    build:
      context: .
    links:
      - webapp
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host